import type { PrivateBucket } from "@/services/storage";
import {
  createEmailSendHandler,
  createResendEmailProvider,
} from "@/workers/handlers/email-send";
import { createPdfRenderHandler } from "@/workers/handlers/pdf-render";
import type { EmailSendMessage, PdfRenderMessage } from "@/workers/messages";
import { processQueueBatch, type QueueBatch } from "@/workers/queue-consumer";
import openNextWorker, {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
  // @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
} from "../.open-next/worker.js";

export { BucketCachePurge, DOQueueHandler, DOShardedTagCache };

type QueueEnv = CloudflareEnv & {
  STORAGE_BUCKET: PrivateBucket;
  RESEND_API_KEY?: string;
  RESEND_FROM_EMAIL?: string;
  BETTER_AUTH_URL?: string;
};

interface CloudflareQueueMessage {
  body: unknown;
  attempts: number;
  ack(): void;
  retry(options?: { delaySeconds?: number }): void;
}

interface CloudflareMessageBatch {
  messages: CloudflareQueueMessage[];
}

async function queue(
  batch: CloudflareMessageBatch,
  env: QueueEnv,
): Promise<void> {
  const adaptedBatch: QueueBatch = {
    messages: batch.messages.map((message) => ({
      body: message.body,
      attempts: message.attempts,
      ack: () => message.ack(),
      retry: (options) => message.retry(options),
    })),
  };

  const renderPdf = createPdfRenderHandler({ bucket: env.STORAGE_BUCKET });
  const sendEmail = createEmailSendHandler({
    provider: createResendEmailProvider({
      apiKey: env.RESEND_API_KEY ?? "",
      from: env.RESEND_FROM_EMAIL ?? "facturas@invoiceflash.app",
    }),
    appBaseUrl: env.BETTER_AUTH_URL ?? "http://localhost:3000",
  });

  await processQueueBatch(adaptedBatch, {
    renderPdf: (message: PdfRenderMessage) => renderPdf(message),
    sendEmail: (message: EmailSendMessage) => sendEmail(message),
  });
}

export default {
  ...openNextWorker,
  queue,
};
